### ISSUE TITLE
Support namespace hierarchy

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.Transport.AzureServiceBus#20]
I would like to request that the namespace hierarchy feature from the full framework transport is added to this one. See: https://docs.particular.net/transports/azure-service-bus/namespace-hierarchy

I would like to use one Service Bus namespace for multiple dev/test environments, rather than paying for several namespaces.

The workaround right now is to customize the endpoint name to have a prefix/suffix with something that uniquely identifies the environment. Forward slashes are not supported, as currently the topic subscriptions are named with the queue names. 

Having to change the endpoint name is not ideal as now this affects how the tables are named when using SqlPersistence (and I assume other persistence libraries). We routinely copy databases from Prod into Dev/Test and now these tables are going to be named different per environment.

It doesn't have to be as powerful as the one in the full ASB transport. Something that looks like below would work nicely:

```c#
endpointConfiguration.UseTransport<AzureServiceBusTransport>().PathGenerator(name => "dev1/")
```

Using the above code, if the endpoint is named "Sender", it would then create a queue called "dev1/Sender", a topic called "dev1/bundle-1" and then in SqlPersistence the tables would continue to be named Sender_OutboxData, Sender_SomeSaga"

**Comment by SeanFeldman** [comment]
One of the major downsides of the namespace hierarchy feature in the old transport was the requirement for all communicating endpoints to configure the same prefix. Failure to comply with this requirement would mean endpoints failing to communicate with each other.
Looking at the request, it's about using a single namespace by multiple developers to sandbox their work. This problem has already been solved by Azure Service Bus service when using Standard Tier. Unlike Premium (which is intended for production), when paid for, it allows to provision **multiple** namespaces. Unfortunately, it's not that well documented. From the service pricing documentation, under ["Will I be charged multiple base charges if I have multiple standard namespaces in my Azure subscription?" FAQ](https://azure.microsoft.com/en-ca/pricing/details/service-bus/):

> No, the standard base charge is billed only once per month per Azure subscription. This means that after you create a single standard tier Service Bus namespace, you will be able to create as many additional standard tier namespaces as you like under that same Azure subscription without incurring additional base charges.

Which has the following benefits:

1. Sandboxing development/testing by **namespace** rather than entity name.
2. Identical entity names in all environments w/o the need to complicate those with prefixes.
3. Better performance (somewhat) and less throttling as you have less contention between your developers, fighting over the same resource in addition to some other neighbors you don't even know might be using service at that time.
4. No need to communicate/share across the team connection string when it's reset. Each namespace has its own credentials.
5. Each MSDN subscription provides [monthly Azure credit fro free](https://azure.microsoft.com/en-ca/pricing/member-offers/credit-for-visual-studio-subscribers/) that could be used not only towards a separate namespace, but an Azure subscription, allowing complete isolation from the rest of your development team for further sandboxing. Unless this credit is utilized for something else, no reason not to use it.

Given the reasons above, would you agree that the feature is not as necessary as it might appear at the first glance?

**Comment by markgould** [comment]
@SeanFeldman - that is perfect. I did not realize that and I agree, I wish they had documented that better.

We can consider this resolved 👍

**Comment by peto268** [comment]
I believe this would be a useful feature even if there is the possibility to create many separate standard namespaces.
It's just easier to have the option to specify:
```
endpointConfiguration.UseTransport<AzureServiceBusTransport>().PathGenerator(name => "dev1/")
```
than to provision a new azure resource and update the transport connection string.

We are currently migrating from the SQL transport to ASB. We use custom transport schema names to quickly spin up somewhat isolated testing environments. We have a main testing environment deployed as a Azure App Service that is using a single DB for business data and NSB. The NSB schema name is generated from the App Service slot name, the main site is using the "NServiceBus" schema. If you create a new App Service slot it will use the same DB, but a different NSB schema name, "NServiceBus.test1" for example. You are still using the same business data, but the two slots don't process each other messages. You can test a feature branch on the slot and be sure the NSB messages will stay inside that one slot.

**Comment by danielmarbach** [comment]
@peto268 Just curious. Why do you think it is easier to define a PathGenerator instead of just providing a clean new namespace via environment-specific variables (which can be scoped to the slots in the App Service)? With a clean namespace, there will never be any overlap at all and that is guaranteed by design.

**Comment by peto268** [comment]
@danielmarbach It's easier because I don't need to provision a new Azure resource.

**Comment by danielmarbach** [comment]
```
az servicebus namespace create --name newnamespace --resource-group yourgroup --location westeurope --tags ... --sku Standard
```
That's all you need

you can even do that with github actions in a few lines

[Login and Setup](https://github.com/danielmarbach/AzureServiceBusGithubActionSpike/blob/main/.github/workflows/main.yml#L23-L40)
[Teardown](https://github.com/danielmarbach/AzureServiceBusGithubActionSpike/blob/main/.github/workflows/main.yml#L50-L56)

**Comment by peto268** [comment]
I still need a user who is allowed to provision Azure resources + doing that directly from the AppService will be a bit more code.
I'm aware that it's not a big issue to just provision separate namespaces per dev/slot/whatever. I just wanted to point out that the namespace hierarchy might be a useful feature.

**Comment by danielmarbach** [comment]
Ok thanks for the feedback and the hint!
