### ISSUE TITLE
Customize native outgoing message

### ISSUE THREAD

**Issue by drcgg** [Particular/NServiceBus.Transport.AzureServiceBus#202]
We are asking NSB team to provide access to outgoing native ASB message via pipeline just like described here but for incoming messages: https://docs.particular.net/transports/azure-service-bus/native-message-access

**Comment by SeanFeldman** [comment]
@drcgg thank you for your request. Could you please explain here the reason you're looking to access native messages sent out for the sake of discussion? Thank you.

**Comment by drcgg** [comment]
We are specifically looking to set message.PartitionKey property before the message is dispatched to broker.

**Comment by SeanFeldman** [comment]
Is there a specific reason to override the ASB message `PartitionKey`? If the destination is a partitioned entity, the message partition key will be assigned a value of hashed message ID. That ensures messages are distributed among the broker partitions and in case of failure of one of the partitions, messages from the other partitions still can be processed.

Also, how would you envision (pseudo-code may be) assigning values to the PartitionKey when given a native message?

**Comment by drcgg** [comment]
We would like to assign one value to a PartitionKey for a group of messages that should remain on a single partition. Another group of messages would be assigned another PartitionKey value that would most likely end up on another partition. If my understanding is correct, ASB Standard Tier Broker would then serve up semi-randomly messages from both partitions. This would provide us a better user experience "fairness" and a 10 msgs from one client would not have to be blocked by previous 1000 msgs from another.

Our initial POC looks very promising, we based our testing on this project:
https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/PartitionedQueues

**Comment by SeanFeldman** [comment]
I'll point out that partitioning is not about fairness but availability. The fact that messages are served from semi-randomly selected partitions is also true for the messages that do not have their partition key set explicitly ([source](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning)):

> In the absence of a partition key, Service Bus distributes messages in a round-robin fashion to all the partitions of the partitioned queue or topic. If the chosen partition is not available, Service Bus assigns the message to a different partition. This way, the send operation succeeds despite the temporary unavailability of a messaging store.

I understand that you've been experimenting with the scenario described above using 2 users and setting a partition key per user. Was your POC also executed again the number of users larger than 16 (maximum number of partitions)?

@axisc, do you know if setting an explicit `PartitionKey` would provide an improvement over having the internal hashing algorithm derive the partition when handling a multi-user scenario @drcgg is targeting when the objective is to achieve some sort of fairness during message _processing_? Thank you.

**Comment by axisc** [comment]
I'd refrain from utilizing partitioning as a way to implement fairness.

@drcgg - the behavior you see is not a promise (even if it's promising), so it's not a good idea to design around that. If the Service Bus can't guarantee it, there is no guarantee. Your understanding is generally correct, but, this is likely and semi-random logic. @SeanFeldman's point is also valid that partitioning was just a way to provide greater availability.

The simplest solution to ensure fairness would be to utilize topics and subscriptions for the below 2 reasons (at the very least).
  * As your workloads grow you can take the same topology to the Premium tier. (Premium doesn't support partitions because it has dedicated resources and we don't need to have additional concepts to provide better availability).
  * The behavior with Topics and Subscriptions is deterministic and you can design your architecture based on that promise.

Hope this helps.

**Comment by drcgg** [comment]
Thank you for your help with this. I understand its not guaranteed and only available in standard tier and I accept these constraints.

**Comment by SeanFeldman** [comment]
This feature has been [released](https://discuss.particular.net/t/nservicebus-transport-azureservicebus-1-7-0-minor-release-available/2193).
