### ISSUE TITLE
AzureServiceBusTransport subscriber to topic

### ISSUE THREAD

**Issue by Claker** [Particular/NServiceBus.Transport.AzureServiceBus#208]
**Describe the bug**
I am not sure if this is a bug but it is also not a feature request.
I want to setup a .net core subscriber handler in a console application I do not manage to get the handler handle the message.

Main issue: This command does not exist for AzureServiceBusTransport:
`transport.Routing().RegisterPublisher(typeof(OrderReceived), "Publisher");`

Do you have any example of using NServiceBus Subscriber with .Net Core? I found none.

I am sure it must come from the configuration but the Particular website has no example for subscribers.
I managed to publish a message to a topic and I see the message is awaiting in the subscription in Azure Service Bus subscription but it is not consumed.

            var endpointConfiguration = new EndpointConfiguration("EventConsumer2");
            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString(ConfigurationManager.AppSettings["ConnectionString"]);

            var endpoint = await Endpoint.Start(endpointConfiguration).ConfigureAwait(false);`

**Comment by SeanFeldman** [comment]
Azure Service Bus transport uses native pub/sub and does not require registration of publisher.
To consumer an event you have to have an endpoint (could be the same that is publishing if it's not send-only) with handler that processes the event.

**Comment by Claker** [comment]
Hi @SeanFeldman ,
I really appreciate your fast response.
I did follow the steps you mention and the example is here:
https://github.com/Claker/ExampleNServiceBus/tree/main

ClientUi endpoint Sends a message (a command) to a queue, then one command handler gets the message and publishes an event. The event containing the right message arrives correctly in Azure and I can see it in the subscription.
However, the handler does not get it.

Can you please advice what is wrong with my code?
Thank you!

Note: the connectionString represents the connectionString to Azure Service Bus

As mentioned before,

**Comment by Claker** [comment]
I would also mention that I understand NServiceBus cannot create the infrastructure, hence, I created the endpoint queues, topics and subscriptions manually(for now) as I am still experimenting with NServiceBus.

If everything goes well, the company I work for, will want to use NServiceBus for majority of our applications.
Thanks

**Comment by SeanFeldman** [comment]
> I would also mention that I understand NServiceBus cannot create the infrastructure

NServiceBus bus can do that. You'd need to enable installers (`endpointConfiguration.EnableInstallers()`). In some environments it cannot, such as Azure Functions. In that case you need to provision the infrastructure yourself. A [tool offered with the transport](https://docs.particular.net/transports/azure-service-bus/operational-scripting) can help.

I'll look into your code.

**Comment by SeanFeldman** [comment]
The issue is with the endpoint `ExampleCommandConsumer`. It sets the topic name other than the default by using `transport.TopicName("companymigrated")`. But the endpoint consuming the event, [`ExampleEventConsumer`](https://github.com/Claker/ExampleNServiceBus/blob/main/ExampleEventConsumer/Program.cs), doesn't. You either have to set both publishing and subscribing endpoints to use the same topic name or use the default value.

**Comment by Claker** [comment]
> The issue is with the endpoint ExampleCommandConsumer. It sets the topic name other than the default by using transport.TopicName("companymigrated"). But the endpoint consuming the event, ExampleEventConsumer, doesn't. You either have to set both publishing and subscribing endpoints to use the same topic name or use the default value.

Thanks @SeanFeldman . I got it working.

I tried:
- Removing transport.TopicName("companymigrated") from CommandConsumer
- Keeping the TopicName and also adding it to the EventConsumer

And it still did not work so I deleted all topics and EnabledInstaller so it creates the topics and subscriptions as it wants.
I had the same setup as it created but somehow it worked now.

Thanks again for your help! 

Last question: I noticed that there are 2 topics created: 1 named after the CommandHandler (which publishes the event) and one named after the endpoint receiving the event. Why is that and to which topic is the command actually sending the event?

**Comment by SeanFeldman** [comment]
@Claker there should be only one topic. The best place to start is the documentation for the transport that explains it all. [Topology](https://docs.particular.net/transports/azure-service-bus/topology) is explained in details and will visualize what needs to happen in order for the endpoints to communicate.

>  I noticed that there are 2 topics created: 1 named after the CommandHandler (which publishes the event) and one named after the endpoint receiving the event. Why is that and to which topic is the command actually sending the event?

That's because in your original code 2 if 3 endpoints where renaming the shared topic. Starting with a clean slate would fix it.

Glad to hear you're unblocked. Good luck. If you have questions, better to ask those using [support](https://particular.net/support) or [forum](https://discuss.particular.net/). Issue tracker is intended for bugs. Good luck with your project!
