### ISSUE TITLE
TestableMessageHandlerContext doesnt init ContextBag with NServiceBus.NativeMessageCustomizer

### ISSUE THREAD

**Issue by drcgg** [Particular/NServiceBus.Transport.AzureServiceBus#218]
Related to feature #202

TestableMessageHandlerContext doesnt init ContextBag with NServiceBus.NativeMessageCustomizer so when the unit tests runs, the code that customizes message will throw null exception.

**To Reproduce**
handler code:

```c#
public async Task Handle(ItemMapped message, IMessageHandlerContext context)
{        
            var options = new PublishOptions();
            options.CustomizeNativeMessage(context, m => m.Label = “abc”);
            await context.Publish(message, options);
}
```
test code:
```c#
var mockContext = new TestableMessageHandlerContext();
var handler = new ItemMappedHandler(mockValidator.Object, mockStorage);
await handler.Handle(e, mockContext);
```

**Comment by SeanFeldman** [comment]
This would be a new feature that would need to be added to the transport to ensure the testing scenario is supported. While there's no timeline commitment when it will be available, this issue will update when it's out. Thank you @drcgg for bringing this up.

**Comment by timbussmann** [comment]
@drcgg you mentioned that you get a `NullReferenceException`, from my understanding it should be a `KeyNotFoundException` with a message like `No item found in behavior context with key: NServiceBus.NativeMessageCustomizer`. If this is not the case, can you share the full message and stack trace of the exception?

The `KeyNotFoundException`  is going to be fixed with the next major version of the transport.

**Comment by drcgg** [comment]
@timbussmann, you are correct, it is throwing System.Collections.Generic.KeyNotFoundException : No item found in behavior context with key: NServiceBus.NativeMessageCustomizer

**Comment by timbussmann** [comment]
@drcgg ok, that makes sense then. This will be fixed with the next major version. Unfortunately, there is no easy workaround available right now as the required type is private. I think you should be able to use some reflection to work around this though. Is this something that is currently blocking you?

**Comment by drcgg** [comment]
@timbussmann as a quick fix we had to temporarily disable bunch of unit tests in our dev branch, we are blocked from promoting the code to master now. Sounds like it will take a while until you are going to release the next version, if that's the case, I am interested in the reflection workaround that you mentioned.

**Comment by timbussmann** [comment]
@drcgg can you try the following code to setup the necessary types on the testable context:

```
var testableContext = new TestableMessageHandlerContext();
var customizer = Activator.CreateInstance("NServiceBus.Transport.AzureServiceBus", "NServiceBus.NativeMessageCustomizer");
testableContext.Extensions.Set("NServiceBus.NativeMessageCustomizer", customizer.Unwrap());
```

**Comment by drcgg** [comment]
@timbussmann, that works! Thank you! Please close the ticket.

**Comment by timbussmann** [comment]
glad to hear this unblocks you for now 👍

**Comment by danielmarbach** [comment]
@drcgg we are thinking about smoothing out some rough edges here by providing a dedicated helper method inside a testing namespace. A current proposal is available at https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/259.
