### ISSUE TITLE
Implement latest version check

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Transport.AzureServiceBus#461]
Since only the [latest version of a tool is supported](https://docs.particular.net/nservicebus/tools/), the [NServiceBus.Transport.AzureServiceBus.CommandLine](https://www.nuget.org/packages/NServiceBus.Transport.AzureServiceBus.CommandLine) tool should have latest version check functionality like [Particular.AzureTable.Export does](https://github.com/Particular/Particular.AzureTable.Export/blob/20e77bd/src/Particular.AzureTable.Export/ToolVersion.cs#L25).

**Comment by DavidBoike** [comment]
Related issues:

* Azure Service Bus https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/461
* SQS Transport https://github.com/Particular/NServiceBus.AmazonSQS/issues/1212
* SQL Persistence https://github.com/Particular/NServiceBus.Persistence.Sql/issues/853

**Comment by danielmarbach** [comment]
@lailabougria and I have started thinking about this and came to the conclusion the version check is helpful for a tool like the Table Exporter or the timeout migration tool, it doesn't make much sense to enforce using the latest tool for the transport topology setup. 

These are the concerns we have:

- When the transport version is supported, the tool that has the same version should also be supported because it has the same support lifetime as the transport
- The tool version check needs to be executed for every command and subcommand. This means for customers that are using this tool to create multiple endpoints, queues etc. each individual call will have the additional latency that comes with the nuget http calls. This affects CI/CD environments.
- The tool version check depends on reaching out to official nuget sources and the availability of those. It is totally valid to mirror nuget packages locally and have dedicated nuget sources for the enterprise to address the risk of nuget package vulnerabilities. These sources wouldn't be considered and we would have to build features into the CLI tool to fetch from different sources too. 

The only thing that would be helpful to validate is that the transport version used and the CLI version are compatible. That though is not easily buildable at this stage.

Closing this issue for now.
