### ISSUE TITLE
Transaction management for SendsAtomicWithReceive non optimal for long running messages

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.AzureServiceBus#584]
The current implementation immediately starts a transaction. For long running operation this means the transaction timeout needs to be increased. This is especially cumbersome with .NET 6 as that only allows incrementing the default timeout via a undocumented reflection based workaround.

All this isn't needed as the transaction only needs to be created during the dispatch stage after all handlers have been invoked and all batched transport operations need to be dispatched to the transport.

The dispatching of at most 100 messages should never exceed the default maximum transaction timeout.

## Solution suggestion

Solution would be to only create the transaction AFTER all handlers have been invoked thus when actual batched message are being dispatched. This might require a change in in the transport API too if that API semantics does not allow to manage such a transaction itself.

This would follow the ASBS sample code on how to deal with transactions.

```c#
ServiceBusReceivedMessage receivedMessage = await receiverA.ReceiveMessageAsync();

// Do all message processing here, no need to start transaction earlier.

using (var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    await receiverA.CompleteMessageAsync(receivedMessage);
    await senderB.SendMessageAsync(new ServiceBusMessage());
    await senderC.SendMessageAsync(new ServiceBusMessage());
    ts.Complete();
}
```

Using this method also makes it possible to refactor away the current complex transaction management via a `CommittableTransaction` to prevent a `TransactionScope` during message processing.

**Comment by SeanFeldman** [comment]
> This is especially cumbersome with .NET 6 as that only allows incrementing the default timeout via a undocumented reflection based workaround.

This has been the case since .NET Core and the release of this transport.

**Comment by danielmarbach** [comment]
> Using this method also makes it possible to refactor away the current complex transaction management via a CommittableTransaction to prevent a TransactionScope during message processing

I don't think this statement is correct. The transaction needs to be shared with the pump and the dispatcher. The commitable transaction approach makes sure we do not span a scope that other things accidentally enlisten. 

@ramonsmits @SeanFeldman I was thinking about this a bit. In theory since we switched to using the `CommitableTransaction` approach the following would enable opening the transaction very late in the game. The pump could add `Lazy<CommittableTransaction>` with `LazyThreadSafetyMode.ExecutionAndPublication`. Then when the dispatcher requires the transaction it gets created then when actually needed but can still be shared with the pump.

**Comment by danielmarbach** [comment]
Here we go a quick "spike" https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/661
