### ISSUE TITLE
SendsAtomicWithReceive and recoverability are not working with large number of outgoing messages

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Transport.AzureServiceBus#817]
#### Description

When sending a large number of messages from a handler in an endpoint configured with `SendsAtomicWithReceive` transport transaction mode, both the transport transaction mode guarantee and recoverability feature are not working as expected.

#### Expected behaviour

1. There should be no ghost messages in the destination queue upon failed dispatch as per [documentation](https://docs.particular.net/transports/transactions#transactions-transport-transaction-sends-atomic-with-receive-consistency-guarantees).
2. A failed processing incoming message should be moved to the error queue after all recoverability attempts have been exhausted as per [documentation](https://docs.particular.net/nservicebus/recoverability/#fault-handling).

#### Actual behaviour

1. Ghost messages are dispatched. Spooky!
2. The failing message is retried infinitely and is never moved to the error queue.

#### Versions

`NServiceBus` 7.8.2
`NServiceBus.Transport.AzureServiceBus` 2.0.5
.NET 6 and 7

### Steps to reproduce

A solution (GitHub repo [here](https://github.com/SeanFeldman/nsb.asb-817/)) with `Trigger` and `Processor` endpoints.
The `Trigger` project sends to self a `Kickoff` message. When the message is handled, it emits more than 100 messages designated for the `Processor`. For demonstration purposes, the number of emitted messages is 500.

```c#
public class KickoffHandler : IHandleMessages<Kickoff>
{
    public async Task Handle(Kickoff message, IMessageHandlerContext context)
    {
        Console.WriteLine("Processing Kickoff message...");

        for (int i = 1; i <= 500; i++)
        {
            await context.Send("processor", new ProcessInstruction { Id = i });
        }

        Console.WriteLine("Done processing Kickoff message");
    }
}
```

To observe the incorrect behaviour, the `Processor` endpoint should not be running, but its queue should exist.

The `Trigger` endpoint is configured to disable recoverability, which should result in the erroring `Kickoff` message being moved to the error queue upon the first failure. The following is the `Trigger` endpoint configuration code.

```c#
var configuration = new EndpointConfiguration("trigger");
var transport = configuration.UseTransport<AzureServiceBusTransport>();
transport.Transactions(TransportTransactionMode.SendsAtomicWithReceive);
transport.ConnectionString(Connections.AzureServiceBus);

configuration.SendFailedMessagesTo("error");
configuration.Recoverability().Delayed(settings => settings.NumberOfRetries(0));
configuration.Recoverability().Immediate(settings => settings.NumberOfRetries(0));
configuration.EnableInstallers();
```

### Additional Information

After starting and running `Trigger` for a while, the following can be observed:

![image](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/assets/1309622/0508c665-7e0b-461b-bbfe-4538057f0cb8)

On the **`Trigger`** queue properties:

![image](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/assets/1309622/d9b5333d-9cb6-44f0-b6b9-6e5a0f035089)

The incoming message is **never** moved to the error queue. The delivery count keeps growing.

<img width="226" alt="image" src="https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/assets/1309622/0a173c92-2176-4266-b0f0-c56e9d44f6a8">

**Comment by SeanFeldman** [comment]
cc @dbelcham

**Comment by soujay** [comment]
@SeanFeldman - Thank you for reporting the bug. The issue has been triaged and we have  prioritized your issue. We'll work on it as of now to release the fix as soon as we can.

**Comment by mikeminutillo** [comment]
I've been able to partially replicate this using the repro code (thanks @SeanFeldman). I did get phantom messages but the message was moved to the error queue on the second processing attempt. Strangely, the first time  I ran it, I got no phantom messages and the message went to the error queue. The second time I got no phantom messages but the message went back to the input queue. On the second processing attempt (after the lock duration of 5 mins) I got phantom messages and the message went to the error queue.

**Comment by SeanFeldman** [comment]
The outcome is highly dependant on the throughout of the namespace in you, I suspect. Bump the number of the outgoing messages to 1000 and you'll see a more consistent (incorrect) behavior.

This all stems from the underlying implementation that I suspect was either nether validated by those using `SendsAtomicWithReceive` as they are well trained not to exceed 100 messages or there are more usages of a lower guarantee. Could be both.

**Comment by dbelcham** [comment]
Any update on a possible resolution for this issue?

**Comment by mikeminutillo** [comment]
We're still investigating the root cause. I believe that there's two things going on.

1. In the dispatcher, [we create a temporary transaction scope that wraps the incoming receive operation](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/release-2.0/src/Transport/Sending/MessageDispatcher.cs#L53-L59). There's a race condition where we might close the scope before the send operation has enlisted in it. That appears to be the root cause of the ghost messages. As we don't flow the receive transaction on the async context, that means that these messages are sent outside of a transaction scope.
2. In the receiver, [if we take too long to process the incoming message, then we lose the message lock before the incoming message can be moved to the error queue](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/release-2.0/src/Transport/Receiving/MessagePump.cs#L287-L290). This means the message remains in the input queue. Unfortunately, this is only logged at the debug level so you're likely not seeing it in the logs.

**Comment by mikeminutillo** [comment]
I believe that https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/833 will fix issue 1 and improve the visibility of issue 2.

We will be working to release a patch that includes the patch but if it's taking a while to process the incoming message you will still likely end up with a message stuck in the input queue.

Extending the lock duration might improve issue 2 (although it will also delay processing messages when endpoints fail). Eyeballing v3 of the transport, it looks like it will not have the same issue but we're still testing that. If you're able to upgrade the impacted endpoint to NServiceBus v8 and v3 of the transport, I believe it should be able to handle this message properly.

**Comment by SeanFeldman** [comment]
If there are more than 100 outgoing messages, those will be divided between 5 batches, but each batch would be under its own transaction scope while using the same incoming message. And [that](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/e9e4e18ed35c35e6614a9ee6bfa4b8b9f87803f9/src/Transport/Sending/MessageDispatcher.cs#L188-L191) doesn't seem right.

**Comment by lailabougria** [comment]
Thanks @dbelcham and @SeanFeldman, for the feedback. I just reproduced the same behavior; we'll be working to resolve this ASAP.

**Comment by lailabougria** [comment]
@dbelcham Given the possibility of message loss both you and I observed when manually running the repro-code, we chose to focus on figuring out what's wrong in the 3.2.0 version first.

We now have an [automated test that mimics the same scenario](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/834), we've ran it a multitude of times (locally and on the build server) and cannot reproduce any type of message loss. The message always ends up in the error queue. 

Looking at those results, the only logical explanation we can come up with for the behavior we observed when manually running the repro, is that there might have been an eventual-consistency issue in the Service Bus Explorer or they're sitting in the transfer queue of the trigger-queue (which you only see in the details), because we haven't even been able to reproduce the same behavior manually since. We also ran the same scenario with a 1000 messages, using the same repro code, and we could see the queue counts out-of-sync, but the end state was exactly as expected, none in the input queue, a 1000 in the error queue.

Would you be willing to review the test and give us any feedback on whether it can be further improved to increase your confidence in any way? At this point in time, given the tests we've done, we believe it's safe to use the latest version of the transport without risking message loss.

Next we'll be focussing on the v2 version: we'll try to find a way to reliably reproduce the failing behavior and verify the PR we raised earlier this week passes all tests.

**Comment by lailabougria** [comment]
@SeanFeldman To your comment, let me add some context on this change.

>If there are more than 100 outgoing messages, those will be divided between 5 batches, but each batch would be under its own transaction scope while using the same incoming message. And [that](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/e9e4e18ed35c35e6614a9ee6bfa4b8b9f87803f9/src/Transport/Sending/MessageDispatcher.cs#L188-L191) doesn't seem right.

In [this PR](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/661), an AzureServiceBusTransportTransaction class was introduced to encapsulate the complexity of the transactionality. It captures the Transaction, which is later used to open a TransactionScope at the latest possible point in time and only when needed. This has been done because of the internal timer that starts ticking when the scope is opened. Opening it late, if we actually need it, avoids unnecessary timeouts. The scope doesn’t own the transaction, it’s the message pump that owns it and commits it.

**Comment by lailabougria** [comment]
@dbelcham @SeanFeldman We were finally able to pinpoint the behavior and traced it down to an issue in the Azure SDK. We raised an issue with the team and provided them with a repo. In case you're interested, [you can follow it](https://github.com/Azure/azure-sdk-for-net/issues/37265).

Both v2 and v3 of the Azure Service Bus transport are affected. However, due to the batching introduced in v3, the odds of this behavior surfacing there are exponentially smaller. That being said, we will introduce a fix for both versions of the transport to prevent this from happening. Since sending more than 100 messages in a single transaction is [not supported by the service](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas), we will detect it and throw early, which means the faulty behavior can never occur.

We're preparing the patch releases with the fix as we speak.

**Comment by SeanFeldman** [comment]
An explicit check for the number of outgoing messages is good. That will remove the dependency on the SDK to do the validate after the messages are attempted for dispatch.

Interestingly enough, I recall that the previous version of the transport, `NServiceBus.AzureServiceBus`, did not require an explicit check for the number of messages in a transaction. If there were more than 100 messages, the SDK [would always throw](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/68430dc861475ed5a132046240f2be5b18ebc7bb/src/Transport/Sending/OutgoingBatchRouter.cs#L147). Version 1 of this transport, a successor to `NServiceBus.AzureServiceBus` has removed the custom exception, allowing the original exception to bubble up. I'd imagine this should be the case for v2/3, as the SDK is the same. The only change I can see is the transition from `TransactionScope` to `CommittableTransaction`.

**Comment by mikeminutillo** [comment]
Creating a `CommittableTransaction` does not set `Transaction.Current`. You ned a `TransactionScope` to do that. The SDK still does throw. The issue is that if you have enough parallel tasks hitting that, the transaction does not properly roll back and that leaves the link in an odd state. Future transactions on the same connection, even with a new transaction and scope, do not complete properly.

**Comment by lailabougria** [comment]
Hey @SeanFeldman @dbelcham,

We've [released patched for both v2 and v3](https://discuss.particular.net/t/nservicebus-transport-azureservicebus-3-2-1-and-2-0-6-patch-releases-available/3638) that address this issue and prevent the SDK issue from surfacing. Please upgrade to the latest version and let us know if you encounter any issues.

Thank you for bringing this issue to our attention and providing us with a repro. Your effort is highly appreciated, it helped us in reproducing the issue quickly.

**Comment by mikeminutillo** [comment]
FYI: We also released a new version of ServiceControl which includes the new version of the transport. See [the announcement](https://discuss.particular.net/t/servicecontrol-4-32-1-patch-release-available/3640) for details and upgrade immediately.
